model_dir: "outputs/erft_sft"
ppo:
  clip_epsilon: 0.2
  gamma: 0.99
  gae_lambda: 0.95
  entropy_coef: 0.01
  policy_lr: 1e-5
  value_lr: 1e-4
  ppo_epochs: 4
  minibatch_size: 4
  episodes_per_update: 8
reward_weights:
  w_final: 1.0
  w_verif: 0.5
  w_round_penalty: 0.1
training:
  total_updates: 20
  save_every: 10
  seed: 42
population:
  enabled: false
  population_size: 4
  pbt_every: 500
  role_mutation_std: 0.02
generation:
  max_new_tokens: 128
  temperature: 0.8
  top_p: 0.95
